# Jenkins deployed via official Helm chart with custom values
# Uses multi-source application to reference external Helm chart with local values
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # Multi-source application: Helm chart from external repo + values from git
  sources:
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 4.12.1
      helm:
        valueFiles:
          - $values/helm/values/jenkins.yaml
    - repoURL: https://github.com/AnishKini007/aws-eks-devops-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
